print("##############################")
print("#                            #")
print("#    Aldira Putri Sholeha    #")
print("#       2210817220024        #")
print("#                            #")
print("##############################")